import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-w-screen">
          <header className="bg-gray-900 text-white">
            <div className="container mx-auto px-4 py-6 flex justify-between items-center">
              <h1 className="text-2xl font-bold">Customer Management</h1>
              <nav>
                <ul className="flex space-x-4">
                  <li>
                    <a href="/">Home</a>
                  </li>
                  <li>
                    <Link href="/customer/create">Create Customer</Link>
                  </li>
                </ul>
              </nav>
            </div>
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
